language: ruby
rvm:
  - 1.9.3
  - 2.2.2
  - 2.4.1
  - ruby-head
env:
  - DB=sqlite
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script:
  - RAILS_ENV=test bunlde exec rake db:migrate --trace
  - bunlde exec rake db:test:prepare
  - bundle exec rspec
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
  allow_failures:
    - rvm: ruby-head
